name: Unit test
on: [push]
jobs:
  Unit-test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '12.x'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: yarn install
      - run: ls ${{ github.workspace }}
      - run: echo "ğŸ‰ Run unit tests"
      - run: yarn test
      - run: echo "ğŸ Tests are ${{ job.status }}."
